version: '3.8'
services:
  db-pipeline:
    image: postgres:13
    container_name: hakibank-db-part2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: hakibank
    ports:
      - "5433:5432"

  backend-pipeline:
    image: python:3.9-slim
    container_name: hakibank-backend-part2
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "pip install -r requirements.txt && python run.py"
    environment:
      DATABASE_URL: postgresql://admin:adminpassword@db-pipeline:5432/hakibank
    ports:
      - "8000:8000" # Part 2 uses 8000
    depends_on:
      - db-pipeline

  frontend-pipeline:
    image: node:18-alpine
    container_name: hakibank-frontend-part2
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build && npm install -g serve && serve -s build -l 3000"
    ports:
      - "3000:3000" # Part 2 uses 3000
    depends_on:
      - backend-pipeline