version: '3.8'

services:
  database:
    image: postgres:13
    container_name: hakibank-db-part1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: hakibank
    volumes:
      - db-data:/var/lib/postgresql/data # This makes data persistent!
    ports:
      - "5432:5432"

  backend:
    image: ichasadullah/hakibank-backend:v1 # Using the image you just pushed!
    container_name: hakibank-backend-part1
    environment:
      DATABASE_URL: postgresql://admin:adminpassword@database:5432/hakibank
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  db-data:
